name: observability-stack

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

volumes:
  prometheus_data:
  grafana_data:

include:
  - services/prometheus/index.yaml
  - services/grafana/index.yaml
  - services/nginx/index.yaml
  - services/frontend/index.yaml

x-peer-common: &peer-common
  build:
    context: ./Kademlia-network
    dockerfile: Dockerfile
  networks:
    monitoring:
  stdin_open: true
  tty: true
  depends_on:
    - bootstrap-node

services:
  bootstrap-node:
    build:
      context: ./Kademlia-network
      dockerfile: Dockerfile
    container_name: bootstrap-node
    networks:
      monitoring:
        ipv4_address: 172.23.0.100
    stdin_open: true
    tty: true
    environment:
      - VAULT_SECRET_PASS=admin
    depends_on:
      - Prometheus
      - Grafana
    command: ["java", "-cp", "/app/p2p-node.jar", "org.graph.server.LauncherBootstrap", "172.23.0.100", "5001", "9001", "8080"]

  peer-8001:
    <<: *peer-common
    container_name: peer-8001
    networks:
      monitoring:
        ipv4_address: 172.23.0.11
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 1 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.11 9002 172.23.0.100 10001 8001"]

  peer-8002:
    <<: *peer-common
    container_name: peer-8002
    networks:
      monitoring:
        ipv4_address: 172.23.0.12
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 2 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.12 9003 172.23.0.100 10002 8002"]

  peer-8003:
    <<: *peer-common
    container_name: peer-8003
    networks:
      monitoring:
        ipv4_address: 172.23.0.13
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 3 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.13 9004 172.23.0.100 10003 8003"]

  peer-8004:
    <<: *peer-common
    container_name: peer-8004
    networks:
      monitoring:
        ipv4_address: 172.23.0.14
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 4 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.14 9005 172.23.0.100 10004 8004"]

  peer-8005:
    <<: *peer-common
    container_name: peer-8005
    networks:
      monitoring:
        ipv4_address: 172.23.0.15
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 5 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.15 9006 172.23.0.100 10005 8005"]

  peer-8006:
    <<: *peer-common
    container_name: peer-8006
    networks:
      monitoring:
        ipv4_address: 172.23.0.16
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 6 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.16 9007 172.23.0.100 10006 8006"]

  peer-8007:
    <<: *peer-common
    container_name: peer-8007
    networks:
      monitoring:
        ipv4_address: 172.23.0.17
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 7 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.17 9008 172.23.0.100 10007 8007"]

  peer-8008:
    <<: *peer-common
    container_name: peer-8008
    networks:
      monitoring:
        ipv4_address: 172.23.0.18
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 8 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.18 9009 172.23.0.100 10008 8008"]

  peer-8009:
    <<: *peer-common
    container_name: peer-8009
    networks:
      monitoring:
        ipv4_address: 172.23.0.19
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 9 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.19 9010 172.23.0.100 10009 8009"]

  peer-8010:
    <<: *peer-common
    container_name: peer-8010
    networks:
      monitoring:
        ipv4_address: 172.23.0.20
    environment:
      - VAULT_SECRET_PASS=admin
    command: ["sh", "-c", "sleep 10 && java -cp /app/p2p-node.jar org.graph.server.Launcher 172.23.0.20 9011 172.23.0.100 10010 8010"]