services:
  web-application-firewall:
    build:
      context: ../../waf
      dockerfile: Dockerfile
    container_name: web-application-firewall
    networks:
      monitoring:
        ipv4_address: 172.23.0.254
    ports:
      - '8080:8080'
    depends_on:
      - api-gateway
