services:
  api-gateway:
    build:
      context: . 
      dockerfile: Dockerfile.nginx
    container_name: api-gateway
    networks:
      - monitoring
    ports:
      - "8080:80" 
    depends_on:
      - bootstrap-node