@startuml Diagram Compoment
!define C4P !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()

skinparam component {
  <<gateway>>  BackgroundColor #B3E5FC FontColor Black
  <<security>> BackgroundColor #D1C4E9 FontColor Black
  <<adapter>>  BackgroundColor #FFEB3B FontColor Black
  <<app>>      BackgroundColor #C8E6C9 FontColor Black
  <<infra>>    BackgroundColor #CFD8DC FontColor Black
  <<storage>>  BackgroundColor #FFCDD2 FontColor Black
  <<metrics>>  BackgroundColor #B2EBF2 FontColor Black
}

System(p2pNode, "P2P Node")

Boundary(networkLayer, "Network Layer") {
  Container(gateway, "NetworkGateway", "Java", "gateway")
  Container(gatewayCrypt, "GatewayCrypt", "Java", "gateway")
  Container(metrics, "Metrics & Monitoring", "Java", "metrics")
}

Boundary(securityLayer, "Security Layer") {
  Container(security, "Security Layer", "Java", "security")
  Container(adapter, "Adapter Services", "Java", "adapter")
}

Boundary(coreLayer, "Core") {
  Container(app, "Application Core", "Java", "app")
}

Boundary(dataLayer, "Data Layer") {
  Container(infra, "Infrastructure", "Java", "infra")
  Container(storage, "Storage (Cache/DHT)", "Java", "storage")
}

Rel(p2pNode, gateway, "Connection")
Rel(gateway, security, "raw bytes")
Rel(gateway, metrics, "push processing metrics")
Rel(security, adapter, "sanitized / validated Message")
Rel(adapter, app, "Domain Events")
Rel(app, infra, "Repository calls")
Rel(app, storage, "Persist Block / State")
Rel(infra, storage, "Cache / DHT operations")

Rel(gateway, gatewayCrypt, "encrypted payload")
Rel(gatewayCrypt, infra, "receive data")
Rel(infra, gatewayCrypt, "send/receive crypt data")

@enduml