services:
  react-dashboard:
    build:
      context: ../../client
      dockerfile: Dockerfile
    container_name: react-dashboard
    networks:
      - monitoring
    ports:
      - "3001:3001"
    depends_on:
      - api-gateway