import React, { useState } from "react";
import { LogsList } from "../components/logs/logsList";
import type { LogPayload } from "../../application/model/log";
import { Link } from "react-router";

interface Props {
  targetNodePort: string;
  dataLogs: LogPayload[];
}

export function LogsPage({
  targetNodePort,
  dataLogs,
}: Props) {
  const [notification, setNotification] = useState<{ type: 'success' | 'error', message: string } | null>(null);

  return (
    <main className="max-w-7xl mx-auto p-6 space-y-10">
      <header className="flex flex-col md:flex-row md:items-end md:justify-between gap-4">
        <div className="space-y-2">
          <Link
            to="/index"
            className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg 
                       border border-gray-200 bg-white text-gray-800 shadow-sm 
                       hover:bg-gray-100 transition
                       dark:bg-gray-900 dark:text-gray-100 dark:border-gray-700 dark:hover:bg-gray-800"
          >
            Back
          </Link>

          <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 dark:text-white">
            System Logs
          </h1>

          <p className="text-sm text-gray-600 dark:text-gray-400">
            Monitor and audit internal operations generated by the distributed ledger. <br />
            <span className="font-mono text-indigo-600 font-bold">
              Operational Target Node: {targetNodePort}
            </span>
          </p>
        </div>
      </header>

      {notification && (
        <div className={`p-4 rounded-lg font-mono text-sm shadow-sm border ${
            notification.type === 'success'
            ? 'bg-green-50 border-green-200 text-green-800 dark:bg-green-900/30 dark:border-green-800 dark:text-green-300'
            : 'bg-red-50 border-red-200 text-red-800 dark:bg-red-900/30 dark:border-red-800 dark:text-red-300'
          }`}>
          <strong>{notification.type === 'success' ? 'STATUS [202 ACCEPTED]:' : 'ERRO:'}</strong> {notification.message}
        </div>
      )}

      <section className="space-y-4">
        <LogsList logs={dataLogs} />
      </section>
    </main>
  );
}